# ---
# Conventional HRV Analysis and Performance Evaluation
#
# Description:
# This script implements the analysis part of the simulation study plan. It takes
# the synthetic R-R interval (RRi) data generated by "1-generate_data.R" and
# analyzes it using conventional, windowed techniques. It then quantitatively
# benchmarks these techniques against the known ground-truth trajectories.
#
# The analysis process follows these key steps:
#   1. Source the data generator script to create a synthetic dataset for a
#      chosen scenario.
#   2. Perform a sliding-window analysis to estimate time-domain metrics
#      (mean RR and SDNN).
#   3. Perform a Short-Time Fourier Transform (STFT) analysis to estimate
#      spectral power proportions (VLF, LF, HF).
#   4. Align the stepwise, windowed results with the continuous ground-truth
#      trajectories via interpolation.
#   5. Calculate performance metrics (RMSE and R-squared) to quantify the
#      accuracy of the conventional methods.
#   6. Generate plots to visually compare the reconstructions from the
#      windowed methods against the ground truth.
#
# Author: Matías Castillo-Aguilar
# ---

# 1. --- Load Necessary Libraries and Source Generator Script ---
library(data.table)
library(ggplot2)
library(cowplot)
library(signal)
source("R/_functions.R")

simulated_data <- readRDS("data/simulated_data.RDS")

# 4. --- Main Analysis and Visualization Pipeline ---
metrics <- vector("list", 3)
plots <- vector("list", 3)

# Define parameters for the conventional analysis
WINDOW_SECONDS <- 60 # 2-minute window is common
OVERLAP_PERC <- 0.99  # 99% overlap for smoother estimates
SAMPLING_RATE_HZ <- 2

for (i in 1:3) {

  # Generate the ground-truth data
  sim_data <- simulated_data[[i]]$data

  # --- B. Run Conventional Analyses ---

  # Time-domain analysis
  time_domain_results <- perform_sliding_window_analysis(
    data = sim_data,
    window_sec = WINDOW_SECONDS,
    overlap_perc = OVERLAP_PERC,
    sampling_rate = SAMPLING_RATE_HZ
  )

  # Spectral analysis
  spectral_results <- get_moving_hrv_proportions(
    rr_ms = sim_data$RR,
    rr_times_s = sim_data$t * 60,
    window_size_s = WINDOW_SECONDS,
    step_size_s = 1
  )

  # Interpolate the sparse windowed results to the original high-resolution time vector
  # This allows for a direct, point-by-point comparison with the ground truth
  aligned_results <- data.table(
    t = sim_data$t,
    RR_windowed_interp = approx(time_domain_results$time, time_domain_results$RR_windowed, xout = sim_data$t, rule = 2)$y,
    SDNN_windowed_interp = approx(time_domain_results$time, time_domain_results$SDNN_windowed, xout = sim_data$t, rule = 2)$y,
    p_vlf_stft_interp = approx(spectral_results$time/60, spectral_results$vlf, xout = sim_data$t, rule = 2)$y,
    p_lf_stft_interp = approx(spectral_results$time/60, spectral_results$lf, xout = sim_data$t, rule = 2)$y,
    p_hf_stft_interp = approx(spectral_results$time/60, spectral_results$hf, xout = sim_data$t, rule = 2)$y
  )

  # Join ground truth with aligned estimates
  metrics[[i]]$estimates <- full_comparison_data <- sim_data[aligned_results, on = "t"]

  # Calculate metrics
  # NOTE: STFT/windowed periodogram methods estimate power proportions, so
  # they must be validated against q_j(t) (the implied variance/power
  # share), NOT p_j(t) (which are mixture/amplitude weights and are not
  # the same quantity as a periodogram-based power proportion).
  metrics[[i]]$statistics <- list(
    rr_metrics = calculate_metrics(full_comparison_data$RR_baseline, full_comparison_data$RR_windowed_interp),
    sdnn_metrics = calculate_metrics(full_comparison_data$SDNN_t, full_comparison_data$SDNN_windowed_interp),
    vlf_metrics = calculate_metrics(full_comparison_data$q_vlf, full_comparison_data$p_vlf_stft_interp),
    lf_metrics = calculate_metrics(full_comparison_data$q_lf, full_comparison_data$p_lf_stft_interp),
    hf_metrics = calculate_metrics(full_comparison_data$q_hf, full_comparison_data$p_hf_stft_interp)
  )

  # --- D. Visualize Comparison ---
  legend <- FALSE
  if (i == 3) {
    legend <- NA
  }

  # Plot 1: RR Baseline Reconstruction
  p_rr <- ggplot(full_comparison_data, aes(x = t)) +
    geom_line(aes(y = RR_baseline, color = "Ground truth"), linetype = 6, show.legend = legend) +
    geom_line(aes(y = RR_windowed_interp, color = "Windowed estimate"), show.legend = legend) +
    scale_color_manual(values = c("Ground truth" = "black",
                                  "Windowed estimate" = "dodgerblue")) +
    scale_y_continuous(n.breaks = 4) +
    labs(subtitle = ifelse(i == 1, "Signal trajectory", ""), color = "Line",
         x = "Time (minutes)", y = "ms") +
    theme_classic(base_size = 12)

  # Plot 2: SDNN Reconstruction
  p_sdnn <- ggplot(full_comparison_data, aes(x = t)) +
    geom_line(aes(y = SDNN_t, color = "Ground truth"), linetype = 6, show.legend = legend) +
    geom_line(aes(y = SDNN_windowed_interp, color = "Windowed estimate"), show.legend = legend) +
    scale_color_manual(values = c("Ground truth" = "black",
                                  "Windowed estimate" = "darkorange")) +
    scale_y_continuous(n.breaks = 5) +
    labs(subtitle = ifelse(i == 1, "Signal SDNN", ""), color = "Line",
         x = "Time (minutes)", y = "ms") +
    theme_classic(base_size = 12)

  # Plot 3: Spectral Proportion Reconstruction
  # Ground truth here is q_j(t) (implied power share), the correct target
  # for a power-proportion estimator like STFT -- see note above.
  p_spectral <-
    full_comparison_data[, list(t, q_vlf, q_lf, q_hf,
                                p_vlf_stft_interp, p_lf_stft_interp,
                                p_hf_stft_interp)] |>
    melt(id.vars = "t") |>
    (\(x){
      x[, Line := fifelse(grepl("interp", variable), "Windowed estimate", "Ground truth")]
      x[, Band := fcase(
        grepl("^q_vlf|^p_vlf", variable), "VLF",
        grepl("^q_lf|^p_lf", variable), "LF",
        grepl("^q_hf|^p_hf", variable), "HF"
      )][]
    })() |>
    ggplot(aes(x = t, y = value, linetype = Line, color = Band)) +
    facet_grid(rows = vars(Band)) +
    geom_line(show.legend = legend) +
    scale_color_manual(values = c("HF" = "#0D1164", "LF" = "#640D5F", "VLF" = "#EA2264"),
                       aesthetics = c("color", "fill")) +
    scale_linetype_manual(values = c(6,1)) +
    scale_x_continuous(expand = c(0,0)) +
    scale_y_continuous(limits = 0:1, n.breaks = 5) +
    labs(subtitle = ifelse(i == 1, "Spectral signature", ""),
         x = "Time (minutes)", y = "Proportion of Power", color = "Color", linetype = "Line") +
    theme_classic(base_size = 12)

  # Combine all plots into a final figure
  plots[[i]] <- plot_grid(p_rr, p_sdnn, p_spectral, ncol = 1, rel_heights = c(0.6,0.6,1), align = "hv", axis = "l")
}

error_classic <- lapply(1:3, function(i) {
  metrics[[i]]$statistics |> rbindlist(idcol = "Domain")
}) |> rbindlist(idcol = "Scenario")

names(error_classic) <- c("Scenario", "Domain", "Metric", "Estimate")

saveRDS(error_classic, file = "data/error_stats_classic.RDS")

fig <- ggpubr::ggarrange(plotlist = plots,
                         ncol = 3,
                         align = "hv",
                         widths = c(2,2,3.6),
                         labels = c("(A)", "(B)", "(C)"))

ggsave(filename = "figures/fig-windowed-method.jpeg", fig,
       device = "jpeg", width = 9, height = 9, dpi = 500)
ggsave(filename = "figures/fig-windowed-method.pdf", fig,
       device = "pdf", width = 9, height = 9)
